[[redirects]]
  from = "/api/*"
  to = "http://106.53.46.106:5000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/proxy-image"
  to = "http://106.53.46.106:5000/proxy-image"
  status = 200
  force = true
